<small><small><i>
All the IPython Notebooks in this lecture series by Dr. Milan Parmar are available @ **[GitHub](https://github.com/milaan9/09_Python_NumPy_Module)**
</i></small></small>

# Python NumPy Array: 

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize NumPy arrays from nested Python lists and access it elements.

## NumPy Array Types:

<div>
<img src="img/array.png" width="700"/>
</div>

## Create a NumPy Array

Simplest way to create an array in Numpy is to use Python List

### Load in NumPy Library

In [1]:
import numpy as np

In [2]:
arr = np.arange(24).reshape(4,3,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [3]:
my_list = [1,2,3,4]
type(my_list)

list

To convert python list to a numpy array by using the object **`np.array`**.

In [4]:
numpy_array_from_list = np.array(my_list)
numpy_array_from_list

array([1, 2, 3, 4])

In practice, there is no need to declare a Python List. The operation can be combined.

In [6]:
my_list1  = np.array([1,2,3,4])
my_list1

array([1, 2, 3, 4])

>**NOTE:** Numpy documentation states use of **`np.ndarray`** to create an array. However, this the recommended method

You can also create a numpy array from a Tuple

In [7]:
my_list2 = np.array(range (1,5))
my_list2

array([1, 2, 3, 4])

## Numpy Array basics 

We can initialize numpy arrays from nested Python lists, and access elements using square brackets **`[]`**:

In [11]:
a = np.array([1,2,3]) # Create a 1D array
print(a) 
print(type(a))  # Prints "<class 'numpy.ndarray'>"

[1 2 3]
<class 'numpy.ndarray'>


In [12]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [13]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# Get Dimension
a.ndim

1

In [15]:
b.ndim

2

In [16]:
# Get Shape
b.shape

(2, 3)

In [17]:
# Get Size
a.itemsize

4

In [18]:
# Get Size
b.itemsize

8

In [31]:
# Get total size
a.nbytes  # a.nbytes = a.size * a.itemsize

12

In [32]:
# Get number of elements
a.size

3

In [33]:
c = np.array([[True, False], [False, True]])
c

array([[ True, False],
       [False,  True]])

In [22]:
print(c.size)
print(c.shape) 

4
(2, 2)


In [19]:
a = np.array([1, 2, 3])   # Create a 1d array
print(a)
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Indexing with 3 elements. Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a 2d array
print(b)
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4


## Array datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. The full list of NumPy datatype (dtypes) can be found in the [NumPy documentation](http://docs.scipy.org/doc/numpy/user/basics.types.html).

<div>
<img src="http://docs.scipy.org/doc/numpy/_images/dtype-hierarchy.png" width="600"/>
</div>

The two biggest things to remember are

- Missing values (NaN) cast integer or boolean arrays to floats
- NumPy arrays only have a single dtype for every element
- the object dtype is the fallback

Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. For example:

In [20]:
a = np.array([1,2,3], dtype='int32') # Create a 1D array with int32 type
type(print(a)) 

[1 2 3]


NoneType

In [21]:
# Get Type
a.dtype

dtype('int32')

In [22]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)
b.dtype

[[9. 8. 7.]
 [6. 5. 4.]]


dtype('float64')

In [25]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int32
float64
int64


* **Does a NumPy array have a single dtype or multiple dtypes?**
  - NumPy arrays are homogenous: they only have a single dtype (unlike DataFrames).
  You can have an array that holds mixed types, e.g. `np.array(['a', 1])`, but the
  dtype of that array is `object`, which you probably want to avoid.

You can read all about numpy datatypes in this **[documentation](https://numpy.org/doc/stable/reference/arrays.dtypes.html)**.

### Random number

#### `rand`
Random values in a given shape from a uniform distribution over [0, 1)

In [26]:
np.random.rand(3)

array([0.09886551, 0.08941604, 0.18351859])

In [27]:
np.random.rand(3,5)

array([[0.94652105, 0.49333678, 0.99396733, 0.38278985, 0.05772916],
       [0.60754659, 0.25707482, 0.97334288, 0.71467963, 0.27058727],
       [0.51667371, 0.74637894, 0.95572041, 0.96860043, 0.9051544 ]])

In [28]:
# Random decimal numbers
np.random.rand(4,2)

#or
#np.random.random_sample(a.shape)

array([[0.88541491, 0.90126752],
       [0.22971511, 0.90427172],
       [0.61278434, 0.69399159],
       [0.49402371, 0.8310438 ]])

In [29]:
np.arange(3,19).reshape(4,4)

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

#### `randn`
Return a sample (or samples) from the "standard normal" distribution. Not Uniform.with mean 0 and variance with 1.


In [30]:
np.random.randn(3)

array([-0.0953002 ,  0.28603527, -0.82669665])

In [31]:
np.random.randn(4,3)

array([[ 1.1864671 , -0.66911685, -0.38756843],
       [ 0.48092255,  1.8532061 ,  0.77862438],
       [-0.31526365,  0.63644769,  1.34124477],
       [-1.37427329, -0.53884266, -1.16455921]])

#### `randint`
Return random integers from **low** (inclusive) to **high** (exclusive).

In [32]:
np.random.randint(2,100,20).reshape(5,4)

array([[78, 89,  7, 66],
       [10, 44, 36, 53],
       [29, 22, 12, 33],
       [50, 17, 30, 81],
       [68, 97, 40, 17]])

In [33]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-1, -1, -3],
       [ 0,  3, -4],
       [-1,  3,  4]])

In [34]:
x = np.random.randint(0, 10, 10)
y = np.random.randint(0, 10, 10)
x, y

(array([5, 0, 9, 9, 8, 3, 8, 9, 5, 6]), array([8, 5, 6, 9, 2, 8, 1, 9, 5, 0]))

It's also *sometimes* a more convinient way of writing and thinking about things.

In [35]:
[i + j for i, j in zip(x, y)]

[13, 5, 15, 18, 10, 11, 9, 18, 10, 6]

In [36]:
x + y

array([13,  5, 15, 18, 10, 11,  9, 18, 10,  6])

### Array Attributes and Methods


In [37]:
rana = np.random.randint(1,10,8)
rana

array([8, 6, 9, 6, 8, 4, 9, 3])

#### `max`, `min`, `argmax`, `argmin`

In [44]:
rana

array([7, 1, 3, 8, 5, 8, 9, 3])

In [45]:
rana.max()

9

In [46]:
rana.argmax()

6

In [36]:
rana.min()

1

In [37]:
rana.argmin()

7

### Numpy also provides many functions to create arrays:

In [38]:
# Generating Zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
# All 0s matrix
np.zeros((2,3))  # pass a tupple

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
# Generating Zeros
np.ones(3)       # one function

array([1., 1., 1.])

In [41]:
np.ones(1)*5

array([5.])

In [42]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [48]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [30]:
# Any other number (full_like)
np.full_like(a, 4)

#or np.full(a.shape, 4)

array([4, 4, 4])

In [46]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [35]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.rand(2,2)  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.72327398 0.99966149]
 [0.84083204 0.22028074]]


In [53]:
#Generate matrix

# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 1 1 1 1

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


You can read about other methods of array creation in this **[documentation](https://numpy.org/doc/stable/user/basics.creation.html#arrays-creation)**.